### ISSUE TITLE
Won't compile on windows (idf v4.4.4)

### ISSUE THREAD

**Issue by nlovrens** [jorgenkraghjakobsen/snapclient#46]
Hi,

I am trying to compile on windows and I got some errors, can you please help me. Thank you.

```
c
C:/Espressif/frameworks/esp-idf-v4.4.4/esp-adf/components/audio_hal/driver/es8311/es8311.c: In function 'es8311_codec_init':
C:/Espressif/frameworks/esp-idf-v4.4.4/esp-adf/components/audio_hal/driver/es8311/es8311.c:59:22: error: 'BOARD_PA_GAIN' undeclared (first use in this function)
     .board_pa_gain = BOARD_PA_GAIN,                         \
                      ^~~~~~~~~~~~~
C:/Espressif/frameworks/esp-idf-v4.4.4/esp-adf/components/audio_hal/driver/es8311/es8311.c:501:41: note: in expansion of macro 'ES8311_DAC_VOL_CFG_DEFAULT'
     codec_dac_volume_config_t vol_cfg = ES8311_DAC_VOL_CFG_DEFAULT();
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/esp-idf-v4.4.4/esp-adf/components/audio_hal/driver/es8311/es8311.c:59:22: note: each undeclared identifier is reported only once for each function it appears in
     .board_pa_gain = BOARD_PA_GAIN,                         \
                      ^~~~~~~~~~~~~
C:/Espressif/frameworks/esp-idf-v4.4.4/esp-adf/components/audio_hal/driver/es8311/es8311.c:501:41: note: in expansion of macro 'ES8311_DAC_VOL_CFG_DEFAULT'
     codec_dac_volume_config_t vol_cfg = ES8311_DAC_VOL_CFG_DEFAULT();
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
[1030/1386] Building C object esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/zl38063/api_lib/vprocTwolf_access.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
